/* Copyright (C) 2020 Yusuf Usta.
RECODDED BY AFNANPPLK  
{
    "name": "pranav",
    "description": "pranav is the Modified Version of WhatsAsena, Made By @farhan-dqz with Baileys.",
    "logo": "https://i.imgur.com/ADXSU8e.jpeg",
    "keywords": ["whatsapp", "userbot", "julie", "WhatsAsena", "mwol", "bot", "ai"],
    "repository": "https://github.com/Ajmal-Achu/Nandhutty",
    "website":   "https://github.com/farhan-dqz/Julie-Mwol",
    "success_url": "https://github.com/farhan-dqz/Julie-Mwol",
    "stack": "container",
    "env": {
        "JULIE_SESSION": {
            "description": "Type here yours Asena Session.",
            "required": true
        },
        "SUDO": {
            "description": "Leave blank if you don't know how to use it! Sudo mode; Your number must be an international number. So you should have your number after the country code. Example: 91xxxxxxxxx,0",
            "required": false
        },
        "LANGUAGE": {
            "description": "Bot language.English => en",
            "required": true,
            "value": "en"
        },
        "BGM_FILTER": {
            "description": "If you likes bgm you can write 'true'. Otherwise false",
            "required": false,
            "value": "true"
        },
        "AUTO_STICKER": {
            "description": "If you likes bgm you can write 'true'. Otherwise false",
            "required": false,
            "value": "true"
        },
        "TALKING_PINKY": {
            "description": " Turn your account into a chatbot!",
            "required": true,
            "value": "false"
        },
        "WEL_GIF": {
            "description": "Fill here any gif link if you selected gif as WEELCOME",
            "required": false,
            "value": "false"
        },
        "BYE_GIF": {
            "description": "Fill here any gif link if you selected gif as WEELCOME",
            "required": false,
            "value": "false"
        },
        "ANTİ_LİNK": {
            "description": "Link Blocking System.",
            "required": true,
            "value": "false"
        },
        "AUTO_BİO": {
            "description": " Set true for auto date, time in biography.",
            "required": true,
            "value": "false"
        },
        "HANDLERS": {
            "description": "For commands.",
            "required": true,
            "value": "^[.!;]"
        },
        "FULL_EVA": {
            "description": "Turn your account into a chatbot!",
            "required": true,
            "value": "false"
        },
        "NO_LOG": {
            "description": " Set true if you don't want to see error log.",
            "required": true,
            "value": "false"
        },
        "SEND_READ": {
            "description": "Write true if you want to throw seen.",
            "required": true,
            "value": "true"
        },
        "ALL_CAPTION": {
            "description": "Caption for images and videos generated by pinky bot",
            "required": false,
            "value": "ITS-ME_pranav_V2✓"
        },
        "HEROKU": {
            "description": "If it is running in Heroku, type true.",
            "required": true,
            "value": "true"
        },
        "HEROKU_API_KEY": {
            "description": "Heroku API Key.",
            "required": true
        },
        "MUTE_MESSAGE": {
            "description": "Customizable Mute Message! Use => default, to change back.",
            "required": false,
            "value": "default"
        },
        "TAG_HEADER": {
            "description": "Heading when taging all",
            "required": false,
            "value": "hear me friends"
        },
        "BLOCK_CHAT": {
            "description": "Choose in which chat the bot won't work there. Ex: 905xxxx && 905xxxx-1xxx or 905xxxx,905xxx...",
            "required": false,
            "value": "false"
        },
        "UNMUTE_MESSAGE": {
            "description": "Customizable Unmute Message! Use => default, to change back.",
            "required": false,
            "value": "default"
        },
        "BLOCK_MESSAGE": {
            "description": "Customizable Block Message! Use => default, to change back.",
            "required": false,
            "value": "default"
        },
        "UNBLOCK_MESSAGE": {
            "description": "Customizable Unblock Message! Use => default, to change back.",
            "required": false,
            "value": "default"
        },
        "BOT_NAME": {
            "description": "heading for .list command reply",
            "required": false,
            "value": "•━━━━╼⤏PRANAV⤎╾━━━•"
        },
        "WORK_TYPE": {
            "description": "PRANAV Working Type. If you use “public”, everyone can use the bot. Else if you use “private”, only you can use your bot.",
            "required": true,
            "value": "public"
        },
        "HEROKU_APP_NAME": {
            "description": "Heroku APP Name.",
            "required": true
        },
        "DEBUG": {
            "description": "Debugging",
            "required": true,
            "value": "false"
        },
        "REMOVE_BG_API_KEY": {
            "description": "https://remove.bg",
            "required": false
        },
        "ALIVE_MESSAGE": {
            "description": "Customizable Alive Message! Use => default, to change back.",
            "required": false,
            "value": "\n ```I Am Alive !!!```\n\n```Type``` *.help* ```for commands```"
        },
        "BAN_MESSAGE": {
            "description": "Customizable Ban Message! Use => default, to change back.",
            "required": false,
            "value": "default"
        },
        "SONGD": {
            "description": "Customizable song DOWNLOADING message instead of 'Dowloading your song'",
            "required": true,
            "value": "*Downloading your song*"
        },
        "SONGU": {
            "description": "Customizable song UPLOADING message instead of 'Uploading your song'",
            "required": true,
            "value": "*Feel the song*"
        },
        "ADD_MESSAGE": {
            "description": "Customizable Add Message! Use => default, to change back.",
            "required": false,
            "value": "default"
        },
        "KICKME_MESSAGE": {
            "description": "Customizable Kickme Message! Use => default, to change back.",
            "required": false,
            "value": "default"
        },
        "PROMOTE_MESSAGE": {
            "description": "Customizable Promote Message! Use => default, to change back.",
            "required": false,
            "value": "default"
        },
        "DEMOTE_MESSAGE": {
            "description": "Customizable Demote Message! Use => default, to change back.",
            "required": false,
            "value": "default"
        },
        "AFK_MESSAGE": {
            "description": "Customizable AFK Message! Use => default, to change back.",
            "required": false,
            "value": "default"
        },
        "NO_ONLINE": {
            "description": "Çevrimiçi görünmek istemiyorsanız true yazın. Type true if you don't want to appear online.",
            "required": false,
            "value": "true"
        }
    },
    "addons": [{
      "plan": "heroku-postgresql"
    }],
    "buildpacks": [{
      "url": "heroku-community/apt"
      }]
  }
Plk  
*/

const fs = require("fs");
const path = require("path");
const events = require("./events");
const chalk = require('chalk');
const config = require('./config');
const {WAConnection, MessageType, Presence} = require('@adiwajshing/baileys');
const {Message, StringSession, Image, Video} = require('./whatsasena/');
const { DataTypes } = require('sequelize');
const { getMessage } = require("./plugins/sql/greetings");
const got = require('got');
const axios = require('axios');

// Sql
const WhatsAsenaDB = config.DATABASE.define('WhatsAsena', {
    info: {
      type: DataTypes.STRING,
      allowNull: false
    },
    value: {
        type: DataTypes.TEXT,
        allowNull: false
    }
});

fs.readdirSync('./plugins/sql/').forEach(plugin => {
    if(path.extname(plugin).toLowerCase() == '.js') {
        require('./plugins/sql/' + plugin);
    }
});

const plugindb = require('./plugins/sql/plugin');

// Yalnızca bir kolaylık. https://stackoverflow.com/questions/4974238/javascript-equivalent-of-pythons-format-function //
String.prototype.format = function () {
    var i = 0, args = arguments;
    return this.replace(/{}/g, function () {
      return typeof args[i] != 'undefined' ? args[i++] : '';
   });
};
if (!Date.now) {
    Date.now = function() { return new Date().getTime(); }
}

Array.prototype.remove = function() {
    var what, a = arguments, L = a.length, ax;
    while (L && this.length) {
        what = a[--L];
        while ((ax = this.indexOf(what)) !== -1) {
            this.splice(ax, 1);
        }
    }
    return this;
};

async function whatsAsena () {
    await config.DATABASE.sync();
    var StrSes_Db = await WhatsAsenaDB.findAll({
        where: {
          info: 'StringSession'
        }
    });
    
    
    const conn = new WAConnection();
    conn.version = [2,2121,7];
    const Session = new StringSession();

    conn.logger.level = config.DEBUG ? 'debug' : 'warn';
    var nodb;

    if (StrSes_Db.length < 1) {
        nodb = true;
        conn.loadAuthInfo(Session.deCrypt(config.SESSION)); 
    } else {
        conn.loadAuthInfo(Session.deCrypt(StrSes_Db[0].dataValues.value));
    }

    conn.on ('credentials-updated', async () => {
        console.log(
            chalk.blueBright.italic('✅ Login information updated!')
        );

        const authInfo = conn.base64EncodedAuthInfo();
        if (StrSes_Db.length < 1) {
            await WhatsAsenaDB.create({ info: "StringSession", value: Session.createStringSession(authInfo) });
        } else {
            await StrSes_Db[0].update({ value: Session.createStringSession(authInfo) });
        }
    })    

    conn.on('connecting', async () => {
        console.log(`${chalk.green.bold('Whats')}${chalk.blue.bold('Asena')}
${chalk.white.bold('Version:')} ${chalk.red.bold(config.VERSION)}

${chalk.blue.italic('ℹ️ Connecting to WhatsApp... Please wait.')}`);
    });
    

    conn.on('open', async () => {
        console.log(
            chalk.green.bold('✅ Login successful!')
        );

        console.log(
            chalk.blueBright.italic('⬇️ Installing external plugins...')
        );

        var plugins = await plugindb.PluginDB.findAll();
        plugins.map(async (plugin) => {
            if (!fs.existsSync('./plugins/' + plugin.dataValues.name + '.js')) {
                console.log(plugin.dataValues.name);
                var response = await got(plugin.dataValues.url);
                if (response.statusCode == 200) {
                    fs.writeFileSync('./plugins/' + plugin.dataValues.name + '.js', response.body);
                    require('./plugins/' + plugin.dataValues.name + '.js');
                }     
            }
        });

        console.log(
            chalk.blueBright.italic('⬇️  Installing plugins...')
        );

        fs.readdirSync('./plugins').forEach(plugin => {
            if(path.extname(plugin).toLowerCase() == '.js') {
                require('./plugins/' + plugin);
            }
        });

        console.log(
            chalk.green.bold('Pranav bot working perfectly 👻')
        );
    });
    
    conn.on('chat-update', async m => {
        if (!m.hasNewMessage) return;
        if (!m.messages && !m.count) return;
        let msg = m.messages.all()[0];
        if (msg.key && msg.key.remoteJid == 'status@broadcast') return;

        if (config.NO_ONLINE) {
            await conn.updatePresence(msg.key.remoteJid, Presence.unavailable);
        }

        if (msg.messageStubType === 32 || msg.messageStubType === 28) {
            // Görüşürüz Mesajı
            var gb = await getMessage(msg.key.remoteJid, 'goodbye');
            if (gb !== false) {
                let pp
                try { pp = await conn.getProfilePicture(msg.messageStubParameters[0]); } catch { pp = await conn.getProfilePicture(); }
                await axios.get(pp, {responseType: 'arraybuffer'}).then(async (res) => {
                await conn.sendMessage(msg.key.remoteJid, res.data, MessageType.image, {caption:  gb.message }); });
            }
            return;
        } else if (msg.messageStubType === 27 || msg.messageStubType === 31) {
            // Hoşgeldin Mesajı
            var gb = await getMessage(msg.key.remoteJid);
            if (gb !== false) {
               let pp
                try { pp = await conn.getProfilePicture(msg.messageStubParameters[0]); } catch { pp = await conn.getProfilePicture(); }
                await axios.get(pp, {responseType: 'arraybuffer'}).then(async (res) => {
                await conn.sendMessage(msg.key.remoteJid, res.data, MessageType.image, {caption:  gb.message }); });
            }
            return;
        }

        events.commands.map(
            async (command) =>  {
                if (msg.message && msg.message.imageMessage && msg.message.imageMessage.caption) {
                    var text_msg = msg.message.imageMessage.caption;
                } else if (msg.message && msg.message.videoMessage && msg.message.videoMessage.caption) {
                    var text_msg = msg.message.videoMessage.caption;
                } else if (msg.message) {
                    var text_msg = msg.message.extendedTextMessage === null ? msg.message.conversation : msg.message.extendedTextMessage.text;
                } else {
                    var text_msg = undefined;
                }

                if ((command.on !== undefined && (command.on === 'image' || command.on === 'photo')
                    && msg.message && msg.message.imageMessage !== null && 
                    (command.pattern === undefined || (command.pattern !== undefined && 
                        command.pattern.test(text_msg)))) || 
                    (command.pattern !== undefined && command.pattern.test(text_msg)) || 
                    (command.on !== undefined && command.on === 'text' && text_msg) ||
                    // Video
                    (command.on !== undefined && (command.on === 'video')
                    && msg.message && msg.message.videoMessage !== null && 
                    (command.pattern === undefined || (command.pattern !== undefined && 
                        command.pattern.test(text_msg))))) {

                    let sendMsg = false;
                    var chat = conn.chats.get(msg.key.remoteJid)
                        
                    if ((config.SUDO !== false && msg.key.fromMe === false && command.fromMe === true &&
                        (msg.participant && config.SUDO.includes(',') ? config.SUDO.split(',').includes(msg.participant.split('@')[0]) : msg.participant.split('@')[0] == config.SUDO || config.SUDO.includes(',') ? config.SUDO.split(',').includes(msg.key.remoteJid.split('@')[0]) : msg.key.remoteJid.split('@')[0] == config.SUDO)
                    ) || command.fromMe === msg.key.fromMe || (command.fromMe === false && !msg.key.fromMe)) {
                        if (command.onlyPinned && chat.pin === undefined) return;
                        if (!command.onlyPm === chat.jid.includes('-')) sendMsg = true;
                        else if (command.onlyGroup === chat.jid.includes('-')) sendMsg = true;
                    }
                    
                    else if ((config.MAHN !== false && msg.key.fromMe === false && command.fromMe === true &&
                        (msg.participant && config.MAHN.includes(',') ? config.MAHN.split(',').includes(msg.participant.split('@')[0]) : msg.participant.split('@')[0] == config.MAHN || config.MAHN.includes(',') ? config.MAHN.split(',').includes(msg.key.remoteJid.split('@')[0]) : msg.key.remoteJid.split('@')[0] == config.MAHN)
                    ) || command.fromMe === msg.key.fromMe || (command.fromMe === false && !msg.key.fromMe)) {
                        if (command.onlyPinned && chat.pin === undefined) return;
                        if (!command.onlyPm === chat.jid.includes('-')) sendMsg = true;
                        else if (command.onlyGroup === chat.jid.includes('-')) sendMsg = true;
                    }
    
                    if (sendMsg) {
                        if (config.SEND_READ && command.on === undefined) {
                            await conn.chatRead(msg.key.remoteJid);
                        }
                        
                        var match = text_msg.match(command.pattern);
                        
                        if (command.on !== undefined && (command.on === 'image' || command.on === 'photo' )
                        && msg.message.imageMessage !== null) {
                            whats = new Image(conn, msg);
                        } else if (command.on !== undefined && (command.on === 'video' )
                        && msg.message.videoMessage !== null) {
                            whats = new Video(conn, msg);
                        } else {
                            whats = new Message(conn, msg);
                        }
/*
                        if (command.deleteCommand && msg.key.fromMe) {
                            await whats.delete(); 
                        }
*/
                        try {
                            await command.function(whats, match);
                        } catch (error) {
                            if (config.LANG == 'TR' || config.LANG == 'AZ') {
                                await conn.sendMessage(conn.user.jid, '-- HATA RAPORU [PranavBOT] --' + 
                                    '\n*WhatsAsena bir hata gerçekleşti!*'+
                                    '\n_Bu hata logunda numaranız veya karşı bir tarafın numarası olabilir. Lütfen buna dikkat edin!_' +
                                    '\n_Yardım için Telegram grubumuza yazabilirsiniz._' +
                                    '\n_Bu mesaj sizin numaranıza (kaydedilen mesajlar) gitmiş olmalıdır._\n\n' +
                                    'Gerçekleşen Hata: ' + error + '\n\n'
                                    , MessageType.text);
                            } else {
                                await conn.sendMessage(conn.user.jid, 'PranavBOT_🐱_[error] ' +
                                    '\n\n*👻 ' + error + '*\n'
                                    , MessageType.text);
                            }
                        }
                    }
                }
            }
        )
    });
    
    try {
        await conn.connect();
    } catch {
        if (!nodb) {
            console.log(chalk.red.bold('Eski sürüm stringiniz yenileniyor...'))
            conn.loadAuthInfo(Session.deCrypt(config.SESSION)); 
            try {
                await conn.connect();
            } catch {
                return;
            }
        }
    }
}

whatsAsena();
